name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  # First, we need to reference the test job
  test:
    uses: ./.github/workflows/tests.yml

  pypi-publish:
    name: upload release to PyPI
    needs: test  # This makes it wait for tests to pass
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v2
      - name: Install Flit
        run: pip install flit
      - name: Build Package
        run: flit build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
